import '@/styles/globals.scss';

import Header from '@/components/layouts/Header';
import BtnTop from '@/components/feature/BtnTop';

export const metadata = {
  title: '파이썬 | 위니북스',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <>
      <Header />
      <div className="layout-grow" style={{ height: '200vh' }}>
        <h2>파이썬</h2>
        {children}
      </div>
      <BtnTop />
    </>
  );
}
