services:
  wenivooks:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wenivooks-dev
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - traefik-network
    labels:
      # Traefik 설정
      - "traefik.enable=true"

      # HTTPS 라우터
      - "traefik.http.routers.wenivooks-dev.rule=Host(`dev.wenivops.co.kr`) && PathPrefix(`/services/wenivooks`)"
      - "traefik.http.routers.wenivooks-dev.entrypoints=websecure"
      - "traefik.http.routers.wenivooks-dev.tls=true"
      - "traefik.http.routers.wenivooks-dev.tls.certresolver=myresolver"

      # 서비스 포트 설정
      - "traefik.http.services.wenivooks-dev.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.wenivooks-stripprefix.stripprefix.prefixes=/services/wenivooks"

      # 미들웨어 체인 (순서 중요!)
      - "traefik.http.routers.wenivooks-dev.middlewares=wenivooks-redirect,wenivooks-stripprefix"

      # 슬래시 추가 리다이렉션 미들웨어
      - "traefik.http.middlewares.wenivooks-redirect.redirectregex.regex=^(.*/services/wenivooks/[^/]+)$$"
      - "traefik.http.middlewares.wenivooks-redirect.redirectregex.replacement=$${1}/"
      - "traefik.http.middlewares.wenivooks-redirect.redirectregex.permanent=true"

networks:
  traefik-network:
    external: true