import '@/styles/globals.scss';
import styles from './layout.module.scss';

import SettingProvider from '@/context/SettingContext';
import Body from '@/components/layouts/Body';

export const metadata = {
  title: '위니북스',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko-KR">
      <SettingProvider>
        <Body>
          <div className={styles.layout}>{children}</div>
        </Body>
      </SettingProvider>
    </html>
  );
}
