import '@/styles/globals.scss';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko-KR">
      <body>
        <div className="wrapper">
          <main className="content">{children}</main>
        </div>
      </body>
    </html>
  );
}
