import '@/styles/globals.scss';
import styles from './layout.module.scss';

import SettingProvider from '@/context/SettingContext';
import Body from '@/components/layouts/Body';

export const metadata = {
  title: '위니북스',
  description: 'Generated by create next app',
};

const BeforeFn = () => {
  const savedTheme = localStorage.getItem('theme');
  if (savedTheme !== 'auto' && savedTheme !== null) {
    document.body.classList.add(savedTheme);
  }

  const savedFontStyle = localStorage.getItem('fontStyle');
  if (savedFontStyle !== null) {
    document.body.classList.add(savedFontStyle);
  }

  const savedFontSize = localStorage.getItem('fontSize');

  if (savedFontSize !== null) {
    document.body.classList.add('size' + savedFontSize);
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko-KR">
      <SettingProvider>
        <Body>
          <div className={styles.layout}>{children}</div>{' '}
          <script
            dangerouslySetInnerHTML={{
              __html: `(${String(BeforeFn)})()`,
            }}
          ></script>
        </Body>
      </SettingProvider>
    </html>
  );
}
