import Header from '@/components/layouts/Header';
import BtnTop from '@/components/feature/BtnTop';

import styles from '../python/layout.module.scss';
import searchStyles from '../search/search.module.scss';
import Side from '@/components/layouts/Side';
import classNames from 'classnames';

// export const metadata = {
//   title: '파이썬 | 위니북스',
//   description: 'Generated by create next app',
// };

export default function Layout({ children }) {
  const pythonMenu = require('public/data/pythonMenu.json');

  return (
    <>
      <Header />

      <div className={classNames('layout-grow', styles.wrapper)}>
        <Side data={pythonMenu} />
        <div className={styles.content}>
          <main className={searchStyles.main}>{children}</main>
        </div>
      </div>

      <BtnTop />
    </>
  );
}
